### ISSUE TITLE
Revoke

### ISSUE THREAD

**Issue by sonicoder86** [archived-shomeya/bootstrap-stylus#13]
Can u unpublish this repo from npm? it gets confusing with bootstrap-styl and makes a lot of headache and doesnt even work :/

**Comment by mikeyp** [comment]
I've marked it as deprecated and updated the read me with links to bootstrap-styl:

```
mikey-p /tmp: npm install bootstrap-stylus
npm WARN deprecated bootstrap-stylus@0.2.2: Please see bootstrap-styl https://www.npmjs.com/package/bootstrap-styl
```
